// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, is_liquid) VALUES ($1, $2)
RETURNING id, name, is_liquid, created_at
`

type CreateAccountParams struct {
	Name     string `json:"name"`
	IsLiquid bool   `json:"is_liquid"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.IsLiquid)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsLiquid,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, is_liquid, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsLiquid,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.name, a.is_liquid, a.created_at,
  COALESCE(SUM(CASE WHEN t.is_inflow THEN t.amount ELSE -t.amount END), 0)::numeric(18,2)::text AS balance
FROM accounts a
LEFT JOIN transactions t ON t.account_id = a.id
GROUP BY a.id
ORDER BY (lower(a.name) = 'cash'), a.name
`

type ListAccountsRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	IsLiquid  bool               `json:"is_liquid"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Balance   string             `json:"balance"`
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsLiquid,
			&i.CreatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts SET name = $2, is_liquid = $3 WHERE id = $1
RETURNING id, name, is_liquid, created_at
`

type UpdateAccountParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	IsLiquid bool   `json:"is_liquid"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount, arg.ID, arg.Name, arg.IsLiquid)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsLiquid,
		&i.CreatedAt,
	)
	return i, err
}
