// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, is_liquid, icon, target_amount) VALUES ($1, $2, $3, $4)
RETURNING id, name, is_liquid, icon, target_amount::text AS target_amount, created_at
`

type CreateAccountParams struct {
	Name         string         `json:"name"`
	IsLiquid     bool           `json:"is_liquid"`
	Icon         string         `json:"icon"`
	TargetAmount pgtype.Numeric `json:"target_amount"`
}

// AccountRow is the read projection: target_amount is cast to text so it
// arrives as a nullable decimal string (pgtype.Text), not pgtype.Numeric.
type AccountRow struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	IsLiquid     bool               `json:"is_liquid"`
	Icon         string             `json:"icon"`
	TargetAmount pgtype.Text        `json:"target_amount"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (AccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.IsLiquid,
		arg.Icon,
		arg.TargetAmount,
	)
	var i AccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsLiquid,
		&i.Icon,
		&i.TargetAmount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, is_liquid, icon, target_amount::text AS target_amount, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (AccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i AccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsLiquid,
		&i.Icon,
		&i.TargetAmount,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.name, a.is_liquid, a.icon, a.target_amount::text AS target_amount, a.created_at,
  COALESCE(SUM(CASE WHEN t.is_inflow THEN t.amount ELSE -t.amount END), 0)::numeric(18,2)::text AS balance
FROM accounts a
LEFT JOIN transactions t ON t.account_id = a.id
GROUP BY a.id
ORDER BY (CASE lower(a.name) WHEN 'cash' THEN 1 WHEN 'investment' THEN 2 ELSE 0 END), a.name
`

type ListAccountsRow struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	IsLiquid     bool               `json:"is_liquid"`
	Icon         string             `json:"icon"`
	TargetAmount pgtype.Text        `json:"target_amount"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Balance      string             `json:"balance"`
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsLiquid,
			&i.Icon,
			&i.TargetAmount,
			&i.CreatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts SET name = $2, is_liquid = $3, icon = $4, target_amount = $5 WHERE id = $1
RETURNING id, name, is_liquid, icon, target_amount::text AS target_amount, created_at
`

type UpdateAccountParams struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	IsLiquid     bool           `json:"is_liquid"`
	Icon         string         `json:"icon"`
	TargetAmount pgtype.Numeric `json:"target_amount"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (AccountRow, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.IsLiquid,
		arg.Icon,
		arg.TargetAmount,
	)
	var i AccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsLiquid,
		&i.Icon,
		&i.TargetAmount,
		&i.CreatedAt,
	)
	return i, err
}
