// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, icon, monthly_budget) VALUES ($1, $2, $3)
RETURNING id, name, icon, monthly_budget::text AS monthly_budget, created_at
`

type CreateCategoryParams struct {
	Name          string         `json:"name"`
	Icon          string         `json:"icon"`
	MonthlyBudget pgtype.Numeric `json:"monthly_budget"`
}

// CategoryRow is the read projection: monthly_budget is cast to text so it
// arrives as a nullable decimal string (pgtype.Text), not pgtype.Numeric.
type CategoryRow struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Icon          string             `json:"icon"`
	MonthlyBudget pgtype.Text        `json:"monthly_budget"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Icon, arg.MonthlyBudget)
	var i CategoryRow
	err := row.Scan(&i.ID, &i.Name, &i.Icon, &i.MonthlyBudget, &i.CreatedAt)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, icon, monthly_budget::text AS monthly_budget, created_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (CategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i CategoryRow
	err := row.Scan(&i.ID, &i.Name, &i.Icon, &i.MonthlyBudget, &i.CreatedAt)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, icon, monthly_budget::text AS monthly_budget, created_at FROM categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]CategoryRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryRow
	for rows.Next() {
		var i CategoryRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon, &i.MonthlyBudget, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $2, icon = $3, monthly_budget = $4 WHERE id = $1
RETURNING id, name, icon, monthly_budget::text AS monthly_budget, created_at
`

type UpdateCategoryParams struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Icon          string         `json:"icon"`
	MonthlyBudget pgtype.Numeric `json:"monthly_budget"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (CategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.Icon, arg.MonthlyBudget)
	var i CategoryRow
	err := row.Scan(&i.ID, &i.Name, &i.Icon, &i.MonthlyBudget, &i.CreatedAt)
	return i, err
}
