// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	IsLiquid  bool               `json:"is_liquid"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID              int64              `json:"id"`
	OccurredOn      pgtype.Date        `json:"occurred_on"`
	Description     string             `json:"description"`
	Direction       string             `json:"direction"`
	IsInflow        bool               `json:"is_inflow"`
	Amount          pgtype.Numeric     `json:"amount"`
	AccountID       int64              `json:"account_id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	ProjectID       pgtype.Int8        `json:"project_id"`
	TransferGroupID pgtype.UUID        `json:"transfer_group_id"`
	Tags            []string           `json:"tags"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
