// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurring = `-- name: CreateRecurring :one
INSERT INTO recurring (description, direction, amount, account_id, category_id, day_of_month)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, description, direction, amount, account_id, category_id, day_of_month,
          last_posted, created_at
`

type CreateRecurringParams struct {
	Description string         `json:"description"`
	Direction   string         `json:"direction"`
	Amount      pgtype.Numeric `json:"amount"`
	AccountID   int64          `json:"account_id"`
	CategoryID  pgtype.Int8    `json:"category_id"`
	DayOfMonth  int32          `json:"day_of_month"`
}

// last_posted defaults NULL (never posted) — set only via SetRecurringPosted.
func (q *Queries) CreateRecurring(ctx context.Context, arg CreateRecurringParams) (Recurring, error) {
	row := q.db.QueryRow(ctx, createRecurring,
		arg.Description,
		arg.Direction,
		arg.Amount,
		arg.AccountID,
		arg.CategoryID,
		arg.DayOfMonth,
	)
	var i Recurring
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Direction,
		&i.Amount,
		&i.AccountID,
		&i.CategoryID,
		&i.DayOfMonth,
		&i.LastPosted,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecurring = `-- name: DeleteRecurring :execrows
DELETE FROM recurring WHERE id = $1
`

func (q *Queries) DeleteRecurring(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecurring, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRecurring = `-- name: GetRecurring :one
SELECT id, description, direction, amount, account_id, category_id, day_of_month,
       last_posted, created_at
FROM recurring WHERE id = $1
`

func (q *Queries) GetRecurring(ctx context.Context, id int64) (Recurring, error) {
	row := q.db.QueryRow(ctx, getRecurring, id)
	var i Recurring
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Direction,
		&i.Amount,
		&i.AccountID,
		&i.CategoryID,
		&i.DayOfMonth,
		&i.LastPosted,
		&i.CreatedAt,
	)
	return i, err
}

const listRecurring = `-- name: ListRecurring :many
SELECT id, description, direction, amount, account_id, category_id, day_of_month,
       last_posted, created_at
FROM recurring
ORDER BY description, id
`

func (q *Queries) ListRecurring(ctx context.Context) ([]Recurring, error) {
	rows, err := q.db.Query(ctx, listRecurring)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recurring
	for rows.Next() {
		var i Recurring
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Direction,
			&i.Amount,
			&i.AccountID,
			&i.CategoryID,
			&i.DayOfMonth,
			&i.LastPosted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecurringPosted = `-- name: SetRecurringPosted :exec
UPDATE recurring SET last_posted = $2 WHERE id = $1
`

type SetRecurringPostedParams struct {
	ID         int64       `json:"id"`
	LastPosted pgtype.Date `json:"last_posted"`
}

func (q *Queries) SetRecurringPosted(ctx context.Context, arg SetRecurringPostedParams) error {
	_, err := q.db.Exec(ctx, setRecurringPosted, arg.ID, arg.LastPosted)
	return err
}

const updateRecurring = `-- name: UpdateRecurring :one
UPDATE recurring
SET description = $2, direction = $3, amount = $4, account_id = $5,
    category_id = $6, day_of_month = $7
WHERE id = $1
RETURNING id, description, direction, amount, account_id, category_id, day_of_month,
          last_posted, created_at
`

type UpdateRecurringParams struct {
	ID          int64          `json:"id"`
	Description string         `json:"description"`
	Direction   string         `json:"direction"`
	Amount      pgtype.Numeric `json:"amount"`
	AccountID   int64          `json:"account_id"`
	CategoryID  pgtype.Int8    `json:"category_id"`
	DayOfMonth  int32          `json:"day_of_month"`
}

// last_posted is intentionally untouched: editing a rule never re-arms its cycle.
func (q *Queries) UpdateRecurring(ctx context.Context, arg UpdateRecurringParams) (Recurring, error) {
	row := q.db.QueryRow(ctx, updateRecurring,
		arg.ID,
		arg.Description,
		arg.Direction,
		arg.Amount,
		arg.AccountID,
		arg.CategoryID,
		arg.DayOfMonth,
	)
	var i Recurring
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Direction,
		&i.Amount,
		&i.AccountID,
		&i.CategoryID,
		&i.DayOfMonth,
		&i.LastPosted,
		&i.CreatedAt,
	)
	return i, err
}
