// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const balanceByPeriod = `-- name: BalanceByPeriod :many
SELECT
    date_trunc($1::text, occurred_on)::date AS period,
    COALESCE(SUM(CASE WHEN is_inflow THEN amount ELSE -amount END), 0)::numeric AS net
FROM transactions
WHERE ($2::date IS NULL OR occurred_on <= $2)
GROUP BY period
ORDER BY period
`

type BalanceByPeriodParams struct {
	Bucket string      `json:"bucket"`
	To     pgtype.Date `json:"to"`
}

type BalanceByPeriodRow struct {
	Period pgtype.Date    `json:"period"`
	Net    pgtype.Numeric `json:"net"`
}

// Signed net per period for the cumulative balance trend. No 'from' filter: the
// running total is summed from the earliest row, so prior periods must be present.
func (q *Queries) BalanceByPeriod(ctx context.Context, arg BalanceByPeriodParams) ([]BalanceByPeriodRow, error) {
	rows, err := q.db.Query(ctx, balanceByPeriod, arg.Bucket, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceByPeriodRow
	for rows.Next() {
		var i BalanceByPeriodRow
		if err := rows.Scan(&i.Period, &i.Net); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const balanceTotals = `-- name: BalanceTotals :one

SELECT
    COALESCE(SUM(CASE WHEN t.is_inflow THEN t.amount ELSE -t.amount END), 0)::numeric AS current_balance,
    COALESCE(SUM(CASE WHEN a.is_liquid THEN (CASE WHEN t.is_inflow THEN t.amount ELSE -t.amount END) ELSE 0 END), 0)::numeric AS liquid_balance
FROM transactions t
JOIN accounts a ON a.id = t.account_id
`

type BalanceTotalsRow struct {
	CurrentBalance pgtype.Numeric `json:"current_balance"`
	LiquidBalance  pgtype.Numeric `json:"liquid_balance"`
}

// Read-only aggregations. Everything is derived from transactions on each call;
// nothing here is stored. Sums use COALESCE(...)::numeric so an empty set is 0
// (not NULL) and sqlc types the column as pgtype.Numeric, not interface{}.
// Stock, point-in-time: every row signed by is_inflow (transfers included, they
// move money between accounts). liquid_balance restricts to is_liquid accounts.
func (q *Queries) BalanceTotals(ctx context.Context) (BalanceTotalsRow, error) {
	row := q.db.QueryRow(ctx, balanceTotals)
	var i BalanceTotalsRow
	err := row.Scan(&i.CurrentBalance, &i.LiquidBalance)
	return i, err
}

const cashFlowByPeriod = `-- name: CashFlowByPeriod :many
SELECT
    date_trunc($1::text, occurred_on)::date AS period,
    COALESCE(SUM(CASE WHEN direction = 'income'  THEN amount END), 0)::numeric AS income,
    COALESCE(SUM(CASE WHEN direction = 'expense' THEN amount END), 0)::numeric AS expense
FROM transactions
WHERE direction IN ('income', 'expense')
  AND ($2::date IS NULL OR occurred_on >= $2)
  AND ($3::date   IS NULL OR occurred_on <= $3)
GROUP BY period
ORDER BY period
`

type CashFlowByPeriodParams struct {
	Bucket string      `json:"bucket"`
	From   pgtype.Date `json:"from"`
	To     pgtype.Date `json:"to"`
}

type CashFlowByPeriodRow struct {
	Period  pgtype.Date    `json:"period"`
	Income  pgtype.Numeric `json:"income"`
	Expense pgtype.Numeric `json:"expense"`
}

// Income/expense bucketed by date_trunc(bucket, occurred_on). bucket is validated
// against an allowlist in Go before it reaches here. transfers excluded.
func (q *Queries) CashFlowByPeriod(ctx context.Context, arg CashFlowByPeriodParams) ([]CashFlowByPeriodRow, error) {
	rows, err := q.db.Query(ctx, cashFlowByPeriod, arg.Bucket, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashFlowByPeriodRow
	for rows.Next() {
		var i CashFlowByPeriodRow
		if err := rows.Scan(&i.Period, &i.Income, &i.Expense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryTotals = `-- name: CategoryTotals :many
SELECT
    t.category_id,
    COALESCE(c.name, 'Uncategorized')::text AS name,
    COALESCE(SUM(t.amount), 0)::numeric AS total
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.direction = 'expense'
  AND ($1::date IS NULL OR t.occurred_on >= $1)
  AND ($2::date   IS NULL OR t.occurred_on <= $2)
GROUP BY t.category_id, c.name
ORDER BY total DESC
`

type CategoryTotalsParams struct {
	From pgtype.Date `json:"from"`
	To   pgtype.Date `json:"to"`
}

type CategoryTotalsRow struct {
	CategoryID pgtype.Int8    `json:"category_id"`
	Name       string         `json:"name"`
	Total      pgtype.Numeric `json:"total"`
}

// Expense by category over an optional window; NULL category folds into one
// "Uncategorized" bucket (LEFT JOIN). Highest spend first.
func (q *Queries) CategoryTotals(ctx context.Context, arg CategoryTotalsParams) ([]CategoryTotalsRow, error) {
	rows, err := q.db.Query(ctx, categoryTotals, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryTotalsRow
	for rows.Next() {
		var i CategoryTotalsRow
		if err := rows.Scan(&i.CategoryID, &i.Name, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectTotals = `-- name: ProjectTotals :many
SELECT
    p.id   AS project_id,
    p.name AS name,
    COALESCE(SUM(t.amount), 0)::numeric AS total
FROM transactions t
JOIN projects p ON p.id = t.project_id
WHERE t.direction = 'expense'
  AND ($1::date IS NULL OR t.occurred_on >= $1)
  AND ($2::date   IS NULL OR t.occurred_on <= $2)
GROUP BY p.id, p.name
ORDER BY total DESC
`

type ProjectTotalsParams struct {
	From pgtype.Date `json:"from"`
	To   pgtype.Date `json:"to"`
}

type ProjectTotalsRow struct {
	ProjectID int64          `json:"project_id"`
	Name      string         `json:"name"`
	Total     pgtype.Numeric `json:"total"`
}

// Expense attributed to a project (rows with project_id set) over an optional
// window. Inner join: rows with no project are not a project cost.
func (q *Queries) ProjectTotals(ctx context.Context, arg ProjectTotalsParams) ([]ProjectTotalsRow, error) {
	rows, err := q.db.Query(ctx, projectTotals, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectTotalsRow
	for rows.Next() {
		var i ProjectTotalsRow
		if err := rows.Scan(&i.ProjectID, &i.Name, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const windowTotals = `-- name: WindowTotals :one
SELECT
    COALESCE(SUM(CASE WHEN direction = 'income'  THEN amount END), 0)::numeric AS income,
    COALESCE(SUM(CASE WHEN direction = 'expense' THEN amount END), 0)::numeric AS expense
FROM transactions
WHERE direction IN ('income', 'expense')
  AND ($1::date IS NULL OR occurred_on >= $1)
  AND ($2::date   IS NULL OR occurred_on <= $2)
`

type WindowTotalsParams struct {
	From pgtype.Date `json:"from"`
	To   pgtype.Date `json:"to"`
}

type WindowTotalsRow struct {
	Income  pgtype.Numeric `json:"income"`
	Expense pgtype.Numeric `json:"expense"`
}

// Flow over an optional [from, to] window. transfers excluded from both sides;
// the transfer fee is an expense row, so it counts in expense (and burn).
func (q *Queries) WindowTotals(ctx context.Context, arg WindowTotalsParams) (WindowTotalsRow, error) {
	row := q.db.QueryRow(ctx, windowTotals, arg.From, arg.To)
	var i WindowTotalsRow
	err := row.Scan(&i.Income, &i.Expense)
	return i, err
}
