// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupedTransaction = `-- name: CreateGroupedTransaction :one
INSERT INTO transactions (occurred_on, description, direction, is_inflow, amount,
                          account_id, category_id, project_id, transfer_group_id, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, occurred_on, description, direction, is_inflow, amount, account_id,
          category_id, project_id, transfer_group_id, tags, created_at
`

type CreateGroupedTransactionParams struct {
	OccurredOn      pgtype.Date    `json:"occurred_on"`
	Description     string         `json:"description"`
	Direction       string         `json:"direction"`
	IsInflow        bool           `json:"is_inflow"`
	Amount          pgtype.Numeric `json:"amount"`
	AccountID       int64          `json:"account_id"`
	CategoryID      pgtype.Int8    `json:"category_id"`
	ProjectID       pgtype.Int8    `json:"project_id"`
	TransferGroupID pgtype.UUID    `json:"transfer_group_id"`
	Tags            []string       `json:"tags"`
}

// Insert a transfer leg or fee row carrying a transfer_group_id (the grouped
// counterpart of CreateTransaction, which always leaves the group NULL).
func (q *Queries) CreateGroupedTransaction(ctx context.Context, arg CreateGroupedTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createGroupedTransaction,
		arg.OccurredOn,
		arg.Description,
		arg.Direction,
		arg.IsInflow,
		arg.Amount,
		arg.AccountID,
		arg.CategoryID,
		arg.ProjectID,
		arg.TransferGroupID,
		arg.Tags,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OccurredOn,
		&i.Description,
		&i.Direction,
		&i.IsInflow,
		&i.Amount,
		&i.AccountID,
		&i.CategoryID,
		&i.ProjectID,
		&i.TransferGroupID,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (occurred_on, description, direction, is_inflow, amount,
                          account_id, category_id, project_id, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, occurred_on, description, direction, is_inflow, amount, account_id,
          category_id, project_id, transfer_group_id, tags, created_at
`

type CreateTransactionParams struct {
	OccurredOn  pgtype.Date    `json:"occurred_on"`
	Description string         `json:"description"`
	Direction   string         `json:"direction"`
	IsInflow    bool           `json:"is_inflow"`
	Amount      pgtype.Numeric `json:"amount"`
	AccountID   int64          `json:"account_id"`
	CategoryID  pgtype.Int8    `json:"category_id"`
	ProjectID   pgtype.Int8    `json:"project_id"`
	Tags        []string       `json:"tags"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.OccurredOn,
		arg.Description,
		arg.Direction,
		arg.IsInflow,
		arg.Amount,
		arg.AccountID,
		arg.CategoryID,
		arg.ProjectID,
		arg.Tags,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OccurredOn,
		&i.Description,
		&i.Direction,
		&i.IsInflow,
		&i.Amount,
		&i.AccountID,
		&i.CategoryID,
		&i.ProjectID,
		&i.TransferGroupID,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = $1 AND transfer_group_id IS NULL
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTransferGroup = `-- name: DeleteTransferGroup :execrows
DELETE FROM transactions WHERE transfer_group_id = $1
`

func (q *Queries) DeleteTransferGroup(ctx context.Context, transferGroupID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransferGroup, transferGroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, occurred_on, description, direction, is_inflow, amount, account_id,
       category_id, project_id, transfer_group_id, tags, created_at
FROM transactions WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OccurredOn,
		&i.Description,
		&i.Direction,
		&i.IsInflow,
		&i.Amount,
		&i.AccountID,
		&i.CategoryID,
		&i.ProjectID,
		&i.TransferGroupID,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const getTransferGroup = `-- name: GetTransferGroup :many
SELECT id, occurred_on, description, direction, is_inflow, amount, account_id,
       category_id, project_id, transfer_group_id, tags, created_at
FROM transactions WHERE transfer_group_id = $1 ORDER BY id
`

func (q *Queries) GetTransferGroup(ctx context.Context, transferGroupID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransferGroup, transferGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.OccurredOn,
			&i.Description,
			&i.Direction,
			&i.IsInflow,
			&i.Amount,
			&i.AccountID,
			&i.CategoryID,
			&i.ProjectID,
			&i.TransferGroupID,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, occurred_on, description, direction, is_inflow, amount, account_id,
       category_id, project_id, transfer_group_id, tags, created_at
FROM transactions
WHERE ($1::date IS NULL OR occurred_on >= $1)
  AND ($2::date IS NULL OR occurred_on <= $2)
  AND ($3::bigint IS NULL OR account_id = $3)
  AND ($4::bigint IS NULL OR category_id = $4)
  AND ($5::bigint IS NULL OR project_id = $5)
ORDER BY occurred_on DESC, id DESC
`

type ListTransactionsParams struct {
	From       pgtype.Date `json:"from"`
	To         pgtype.Date `json:"to"`
	AccountID  pgtype.Int8 `json:"account_id"`
	CategoryID pgtype.Int8 `json:"category_id"`
	ProjectID  pgtype.Int8 `json:"project_id"`
}

// All filters are optional; a NULL narg disables that predicate. Newest first.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.From,
		arg.To,
		arg.AccountID,
		arg.CategoryID,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.OccurredOn,
			&i.Description,
			&i.Direction,
			&i.IsInflow,
			&i.Amount,
			&i.AccountID,
			&i.CategoryID,
			&i.ProjectID,
			&i.TransferGroupID,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET occurred_on = $2, description = $3, direction = $4, is_inflow = $5, amount = $6,
    account_id = $7, category_id = $8, project_id = $9, tags = $10
WHERE id = $1 AND transfer_group_id IS NULL
RETURNING id, occurred_on, description, direction, is_inflow, amount, account_id,
          category_id, project_id, transfer_group_id, tags, created_at
`

type UpdateTransactionParams struct {
	ID          int64          `json:"id"`
	OccurredOn  pgtype.Date    `json:"occurred_on"`
	Description string         `json:"description"`
	Direction   string         `json:"direction"`
	IsInflow    bool           `json:"is_inflow"`
	Amount      pgtype.Numeric `json:"amount"`
	AccountID   int64          `json:"account_id"`
	CategoryID  pgtype.Int8    `json:"category_id"`
	ProjectID   pgtype.Int8    `json:"project_id"`
	Tags        []string       `json:"tags"`
}

// Scoped to transfer_group_id IS NULL: transfer legs are immutable via this API
// (managed as a group), so a leg id matches no row and surfaces as not-found.
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.OccurredOn,
		arg.Description,
		arg.Direction,
		arg.IsInflow,
		arg.Amount,
		arg.AccountID,
		arg.CategoryID,
		arg.ProjectID,
		arg.Tags,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OccurredOn,
		&i.Description,
		&i.Direction,
		&i.IsInflow,
		&i.Amount,
		&i.AccountID,
		&i.CategoryID,
		&i.ProjectID,
		&i.TransferGroupID,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}
